//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace problema9.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mostra1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mostra1(string ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mostra1", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mostra1Async(string ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Alta(string ci, string nombres, string paterno, string materno, string fechaNacimiento, string genero, string direccion, string telefono, string celular, string correo, string password, string rol, string departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alta", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AltaAsync(string ci, string nombres, string paterno, string materno, string fechaNacimiento, string genero, string direccion, string telefono, string celular, string correo, string password, string rol, string departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cambio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Cambio(string ci, string nombres, string paterno, string materno, string fechaNacimiento, string genero, string direccion, string telefono, string celular, string correo, string password, string rol, string departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cambio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CambioAsync(string ci, string nombres, string paterno, string materno, string fechaNacimiento, string genero, string direccion, string telefono, string celular, string correo, string password, string rol, string departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Baja", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Baja(string ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Baja", ReplyAction="*")]
        System.Threading.Tasks.Task<int> BajaAsync(string ci);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : problema9.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<problema9.ServiceReference1.WebService1Soap>, problema9.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public System.Data.DataSet mostra1(string ci) {
            return base.Channel.mostra1(ci);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mostra1Async(string ci) {
            return base.Channel.mostra1Async(ci);
        }
        
        public string Alta(string ci, string nombres, string paterno, string materno, string fechaNacimiento, string genero, string direccion, string telefono, string celular, string correo, string password, string rol, string departamento) {
            return base.Channel.Alta(ci, nombres, paterno, materno, fechaNacimiento, genero, direccion, telefono, celular, correo, password, rol, departamento);
        }
        
        public System.Threading.Tasks.Task<string> AltaAsync(string ci, string nombres, string paterno, string materno, string fechaNacimiento, string genero, string direccion, string telefono, string celular, string correo, string password, string rol, string departamento) {
            return base.Channel.AltaAsync(ci, nombres, paterno, materno, fechaNacimiento, genero, direccion, telefono, celular, correo, password, rol, departamento);
        }
        
        public int Cambio(string ci, string nombres, string paterno, string materno, string fechaNacimiento, string genero, string direccion, string telefono, string celular, string correo, string password, string rol, string departamento) {
            return base.Channel.Cambio(ci, nombres, paterno, materno, fechaNacimiento, genero, direccion, telefono, celular, correo, password, rol, departamento);
        }
        
        public System.Threading.Tasks.Task<int> CambioAsync(string ci, string nombres, string paterno, string materno, string fechaNacimiento, string genero, string direccion, string telefono, string celular, string correo, string password, string rol, string departamento) {
            return base.Channel.CambioAsync(ci, nombres, paterno, materno, fechaNacimiento, genero, direccion, telefono, celular, correo, password, rol, departamento);
        }
        
        public int Baja(string ci) {
            return base.Channel.Baja(ci);
        }
        
        public System.Threading.Tasks.Task<int> BajaAsync(string ci) {
            return base.Channel.BajaAsync(ci);
        }
    }
}
